// Hover-tip text for the cockpit controls, keyed by the control's visible label.
// Rendered as a native `title` tooltip on each control label (see the control
// components in App.tsx). Keyed by label so one entry covers a control wherever it
// appears (live panel, cache panel, debug lab) — the same label means the same thing.
export const CONTROL_HINTS: Record<string, string> = {
  "A Curve": "Contrast of the accumulation falloff — higher = sharper, more concentrated hotspots.",
  "A Gain": "Strength of the accumulation effect — higher = bolder buildup where particles cluster.",
  "A Memory": "How long accumulated buildup lingers — higher = trails fade more slowly.",
  "A Radius": "How far each particle's accumulation spreads — higher = wider, softer pools.",
  "A Reject": "Filters out faint noise from accumulation — higher = only strong clusters show.",
  "Alarm": "Prey flee a danger scent trail — higher = sharper escape waves away from predators.",
  "Angle": "Spread of a particle's sensing cone — sets how wide it looks for trails to follow.",
  "Aniso Follow": "Particles steer along the deposited flow — higher = one-way lanes and vortex rings.",
  "Aperture": "Lens opening size — higher = shallower focus, more blur outside the focal distance.",
  "Axial": "Forward/back push along a particle's heading. Higher = stronger thrust along its axis.",
  "Blend": "How particle colors combine onto the canvas (e.g. additive glow vs normal).",
  "Bloom": "Strength of the glowing bloom haze around bright particles.",
  "Bloom Radius": "How far bloom spreads outward. Higher = wider, softer glow.",
  "Bloom Thresh": "Brightness needed to bloom. Higher = only the brightest spots glow.",
  "Boundary": "What happens at the edge: bounce, reset, wrap, tube, stick, soft, or portal.",
  "Brightness Boost": "Relifts dense particle clusters after density exponent shaping. Higher = brighter clumps.",
  "Bright Amt": "How much particle brightness varies between particles. Higher = stronger bright/dim spread.",
  "Bright Curve": "Bias of the brightness spread. Higher = more particles pushed toward the dim end.",
  "Bright Max": "Highest brightness multiplier a particle can get from variation.",
  "Bright Min": "Lowest brightness multiplier a particle can get from variation.",
  "Chemotaxis": "Steer along density gradient — positive climbs into crowds, negative flees them.",
  "Chroma Ab": "Lens color-fringing at edges. Higher = stronger red/blue split.",
  "Cohesion": "How strongly tracked particles pull together — higher = tighter flocking.",
  "Color Amt": "How much particle hue, saturation and shade shift between particles. Higher = more varied.",
  "Color Curve": "Bias of the hue-shift spread. Higher = most particles shift only slightly.",
  "Color Sat": "Color intensity. Higher = richer colors, lower = toward grayscale.",
  "Contrast": "Difference between lights and darks. Higher = punchier, more contrast.",
  "Cutoff": "Trail brightness threshold for rendering — higher = only strong trails show.",
  "Cutoff Prepass": "Computes the density cull in a separate pass for cleaner culling (performance tweak).",
  "D Curve": "Brightness falloff curve — higher = harsher, more concentrated glow.",
  "D Emit": "Overall brightness of the volumetric density glow. Higher = denser, brighter fog.",
  "D Gain": "Emission contrast — higher = brighter cores against darker surroundings.",
  "D Large": "Big-blob noise scale — higher = larger, broader cloud structures.",
  "D Mask": "Cutoff that hides faint density — higher = only dense regions stay visible.",
  "D Occlude": "How much dense fog shadows what's behind it. Higher = deeper, murkier volume.",
  "D Ridges": "Blends solid blobs into thin ridge/filament structures. Higher = wispier.",
  "D Small": "Fine-detail noise scale — higher = smaller, crisper specks and texture.",
  "DOF": "Turns depth-of-field on — blurs particles that aren't at the focus distance.",
  "DOF Blur": "How strong the out-of-focus blur is. Higher = softer, blurrier background.",
  "DOF Debug": "Shows a visual overlay of the focus/blur zones to help you set up depth-of-field.",
  "Demo": "Auto-drifts the controls after 60s idle so the sim keeps showing new looks.",
  "Density": "Overall opacity/glow of the particle field. Higher = thicker, more solid look.",
  "Density Exponent": "Raises particle brightness by density. Higher = suppresses lone haze and emphasizes clumps.",
  "Despeckle": "Post-process cleanup for isolated bright specks. Higher = stronger firefly removal.",
  "Diffuse": "How much trails blur and spread each frame — higher = softer, smokier trails.",
  "Distance": "Camera sensor distance — adjusts perspective depth of the view.",
  "Drag": "Velocity damping — higher = particles slow down faster.",
  "Emit": "Mass each particle lays into trails. Higher = stronger, brighter deposits.",
  "Energy": "Metabolism strength — particles spend energy moving and starve/reset if unfed. 0 = off.",
  "Energy Drain": "Metabolism cost — higher = unfed particles starve and fade faster.",
  "Exposure": "Overall light level. Higher = brighter whole image.",
  "FOV": "Camera field of view — higher = wider, more zoomed-out view.",
  "Filament": "Stretches particles into thread-like strands. Higher = longer, wispier filaments.",
  "Flare": "Strength of anamorphic streaks from bright cores.",
  "Flare Cutoff": "Brightness needed to streak. Higher = only the brightest cores flare.",
  "Flare Height": "Vertical reach of flare streaks, independent of length.",
  "Flare Len": "Horizontal length of the flare streaks. Higher = longer streaks.",
  "Flare Star": "Mixes vertical streaks in. 0 = horizontal only, higher = star-shaped.",
  "Flock Align": "Match neighbors' motion — higher = smoother flocking, murmuration-like flow.",
  "Flock Sep": "Push away from crowding — higher = more spacing, less clumping.",
  "Flow Agree": "Requires neighbors to move the same way to count. Higher = keeps only aligned flows.",
  "Flow Color": "Tints particles by direction of motion. Higher = stronger flow-based coloring; negative flips it.",
  "Focal Dist": "Distance from camera that stays sharp; everything nearer/farther blurs.",
  "Fog Bright": "Brightness of the volumetric fog glow. Higher = denser, brighter haze.",
  "Fog Scale": "Resolution of the fog pass. Lower = softer/faster fog, higher = sharper.",
  "Fog Steps": "Detail of fog ray-marching. Higher = smoother fog but slower.",
  "Fog Tint": "Color of the volumetric fog glow.",
  "Follow": "Makes the camera trail a tracked particle as it moves.",
  "Follow Dist": "How far behind the tracked target the camera stays.",
  "Follow Height": "How high above the tracked target the camera rides.",
  "Follow Smooth": "Softens follow motion — higher = smoother, lagging follow.",
  "Follow Speed": "How fast the camera catches up to the target. Higher = tighter follow.",
  "Force": "Master multiplier on all steering forces — higher = stronger overall movement.",
  "GPU": "WebGPU status: OK if hardware accelerated, Fallback if not.",
  "GPU MB": "Live readout: video memory used by the particle and field buffers, in megabytes.",
  "GS Feed": "Gray-Scott feed rate — higher = faster spreading, more spots fill in.",
  "GS Kill": "Gray-Scott kill rate — tunes pattern type between spots, stripes, and labyrinths.",
  "Gray-Scott": "Reaction-diffusion strength — paints Turing-like spots and maze stripes on the cloud.",
  "Half Large": "Renders the large-scale density at half resolution for speed (slightly softer).",
  "Hazard": "Chance per step a particle randomly dies. Higher = more churn and resets.",
  "Haze Cull": "Hard-removes particles outside dense structure. Higher = more aggressive haze cleanup.",
  "Hue Hi": "High end of the color-variation hue range across particles.",
  "Hue Lo": "Low end of the color-variation hue range across particles.",
  "Initial": "Starting layout of particles: grid, ring, helix, disc, dual, shell, or vortex.",
  "Instant Demo": "Starts the auto-drift demo right away instead of waiting for idle time.",
  "Lateral": "Turning/sideways force strength. Higher = sharper steering toward trails.",
  "Lenia": "Lifelike growth in the density field — patterns grow/shrink toward a target density.",
  "Lenia Mu": "Target density Lenia grows toward — sets the sweet-spot crowding level for growth.",
  "Lenia Sigma": "How forgiving Lenia's target is — wider = grows over a broader density range.",
  "Lock View": "Freezes the camera so orbit/follow/drag can't move it.",
  "Look": "Makes the camera aim at the tracked particle/target.",
  "Look Smooth": "Softens camera aiming — higher = smoother, lazier turns.",
  "Look Speed": "How quickly the camera turns to face its target. Higher = snappier aim.",
  "MIPS": "Crowd-slowdown effect — higher = dense areas clump into spontaneous droplets.",
  "Max FPS": "Caps the frame rate to save power; Off lets it run as fast as it can.",
  "Mix": "How strongly particles align to the fixed orientation axis. 0 = off.",
  "Mutation": "How much each cohort's rule drifts from the base. Higher = more behavior variety.",
  "Neighbors": "Minimum neighbors a particle needs to survive the Support cull. Higher = stricter.",
  "Opacity": "Brightness/opacity of the deposited motion trails.",
  "Opacity Amt": "How much particle opacity varies between particles. Higher = more see-through/solid spread.",
  "Opacity Curve": "Bias of the opacity spread. Higher = more particles pushed toward transparent.",
  "Opacity Max": "Highest opacity multiplier a particle can get from variation.",
  "Opacity Min": "Lowest opacity multiplier a particle can get from variation.",
  "Orbit": "Auto-rotates the camera around the scene continuously.",
  "Orbit Speed": "How fast the camera auto-orbits. Higher = faster spin.",
  "Orient": "What each particle points toward: velocity, up, radial, outward, swirl, or noise.",
  "P Color": "Picks the particle color palette/mapping mode from a curated set of looks.",
  "P Cutoff": "Hides particles in sparse regions below this density. Higher = thins out lonely particles.",
  "P Glow": "Soft radial glow in each particle's core. Higher = brighter halo, less flat disc.",
  "P Hot": "Pushes each particle's center toward white for a hot, blown-out core.",
  "P Keep": "Normalizes brightness by local density so dense and sparse areas look more even.",
  "P Max Px": "Largest a particle can grow to on screen. Clamps the upper size limit.",
  "P Min Px": "Smallest a particle can shrink to on screen. Clamps the lower size limit.",
  "P Opacity": "Overall particle brightness/opacity — the master intensity knob for particles.",
  "P Radius": "Neighborhood size used to measure local density for the cutoff/keep effects.",
  "P Scale": "Base on-screen size of each particle in pixels.",
  "P Slow Cut": "Fades out particles slower than this speed. Higher = hides more sluggish ones.",
  "P Soft": "Softness of the density mask edge. Higher = gentler fade between kept and culled.",
  "P Speed Cut": "Fades out particles moving faster than this speed. Higher = allows faster ones.",
  "P Tint": "Overall color tint multiplied onto every particle.",
  "Palette": "Color theme for particles (e.g. Aurora, Ember).",
  "Particle Color Mode": "Chooses what drives particle color — cohort, velocity, or other sources.",
  "Particles": "How many particles the simulation runs. Higher = denser but heavier to compute.",
  "Persist": "How long trails stay before fading — higher = longer, more lingering trails.",
  "Pitch": "Tilts the camera up/down around the scene.",
  "Predator": "Predator group chases prey scent — higher = faster, tighter hunting pursuit.",
  "Preset": "Load a built-in look — swaps the whole config to a curated starting point.",
  "Pulse": "Amplitude of a breathing throb in the trails. 0 = off; higher = stronger pulsing.",
  "Pulse Rate": "Speed of the trail pulse — higher = faster breathing/throbbing.",
  "Quorum": "Crowd ignition — dense clusters flare brighter, shift hue, and pull inward.",
  "Quorum Thr": "Crowding level needed to ignite — higher = only the densest clumps light up.",
  "Radius": "Size of the trail blob each particle deposits. Higher = thicker, broader trails.",
  "Ray Res": "Render resolution (in p). Higher = sharper image but heavier to draw.",
  "Ray Steps": "Samples per view ray. Higher = crisper volume detail, lower = faster.",
  "Ray Target": "Readout: current render resolution being used (width x height).",
  "Recycle": "Resets particles that drift into empty space back into active regions.",
  "Render": "Which layers to draw — particles, density fog, trails, accumulation, or combinations.",
  "Renderer": "Shows which draw path is active (Live 3D or WebGPU).",
  "Restless": "Random nudge given to nearly-stuck particles. Higher = less freezing in place.",
  "Ribbon %": "Fraction of particles drawn as flowing ribbons instead of dots.",
  "Ribbon Edge Fade": "Softens the side edges of ribbons — higher = feathered, less hard-edged.",
  "Ribbon Fade": "Tapers ribbon width toward its tail — higher = thinner, pointed ends.",
  "Ribbon Fade Start": "Where along the ribbon the tail taper begins — higher = taper starts later.",
  "Ribbon Joints": "Segments per ribbon — higher = smoother curves, more detail.",
  "Ribbon Len": "How many trail points each ribbon spans — higher = longer ribbons.",
  "Ribbon W ×": "Overall ribbon thickness multiplier — higher = wider ribbons.",
  "Saved": "Load one of your saved settings snapshots (or Export/Save the current one).",
  "Scene Gain": "Extra brightness boost on the scene before tone-mapping.",
  "Seed": "Random seed for this run — same seed reproduces the exact same simulation.",
  "Sensor": "How strongly particles sense the trail field. Higher = they react more to trails.",
  "Shape": "Domain shape that confines particles: cube, sphere, cylinder, or pyramid.",
  "Sigma": "Readout: width of the Lenia growth kernel driving the sim's birth/death curve.",
  "Sim Res": "Voxel grid resolution. Higher = finer, more detailed sim (and heavier on GPU).",
  "Sim Speed": "How fast the simulation advances each frame. Higher = motion runs faster.",
  "Size Amt": "How much particle size varies between particles. Higher = stronger big/small spread.",
  "Size Curve": "Bias of the size spread. Higher = more particles pushed toward the small end.",
  "Size Max": "Largest size multiplier a particle can get from variation.",
  "Size Min": "Smallest size multiplier a particle can get from variation.",
  "Species": "Strength of inter-species attract/repel, forming particle-life-style clusters.",
  "Strafe": "Sideways drift strength — higher = particles slide perpendicular to their heading.",
  "Strafe Momentum": "Blends strafe into velocity for damping. Higher = less low-speed ping-pong.",
  "Stretch Max": "Streak length for fast particles — the maximum stretch amount.",
  "Stretch Min": "Streak length for slow particles — the baseline stretch amount.",
  "Stretch Speed": "Speed at which streaks reach full stretch. Lower = stretches at slower speeds.",
  "Supp Smooth": "Blends the Support cull toward smooth field density. Higher = less grid-like blinking.",
  "Supp Rad": "Search radius for counting neighbors in the Support cull. Higher = wider reach.",
  "Support": "Hides particles with too few neighbors. Higher = cull isolated loners, keep clusters.",
  "Sym X": "Mirror behavior across the X axis for left-right symmetric patterns.",
  "Sym Y": "Mirror behavior across the Y axis for up-down symmetric patterns.",
  "Sym Z": "Mirror behavior across the Z axis for front-back symmetric patterns.",
  "Tap": "Readout: number of grid cells each particle stamps into the trail when depositing.",
  "Trail Color": "How trails are colored: by density, flow direction, heat, or a fixed tint.",
  "Trail Scale": "Readout: how strongly particles deposit into the trail volume, scaled by density.",
  "Var Coherence": "Blend from random-per-particle to smooth spatial patches. Higher = neighbors match more.",
  "Var Detail": "Noise lacunarity — higher adds finer, busier detail to the variation field.",
  "Var Drift": "Higher = each particle's traits slowly drift over time instead of staying fixed.",
  "Var Gain": "How much each finer noise layer adds. Higher = rougher, more contrasty variation.",
  "Var Master": "Overall strength of all per-particle variation. Higher = more visible differences.",
  "Var Octaves": "Number of noise layers in the variation field. More = richer, more detailed patterns.",
  "Var Scale": "Spatial frequency of the variation field. Higher = patches change over shorter distances.",
  "Vel Stretch": "Stretches particles into streaks along their direction of motion.",
  "Vign Soft": "How gradual the vignette fade is. Higher = darkness only in corners.",
  "Vignette": "Darkening of the frame edges. Higher = stronger edge shadow.",
  "Voxel": "Readout: world size of one grid cell. Smaller = finer spatial detail.",
  "Yaw": "Rotates the camera left/right around the scene.",
  "Zoom": "How far the camera sits from the scene. Lower = closer in.",
};

export function controlHint(label: string): string | undefined {
  return CONTROL_HINTS[label];
}
