export type ParticleBlendMode = "additive" | "alpha" | "opaque";
export type TrailColorMode = "stable" | "flow" | "thermal" | "tint";

export type RenderControls = {
  density: number;
  exposure: number;
  fov: number;
  aperture: number;
  focusDistance: number;
  dofBlur: number;
  dofEnabled: boolean;
  dofDebug: boolean;
  sceneBrightness: number;
  raySteps: number;
  rayResolution: number;
  fogTemporal: boolean;
  fogRenderScale: number;
  fogStepScale: number;
  fogTemporalBlend: number;
  fogBlueNoise: boolean;
  fieldTextureSampling: boolean;
  emptySpaceSkipping: boolean;
  emptySpaceThreshold: number;
  emptySpaceStride: number;
  particleSizePx: number;
  particleMinPx: number;
  particleMaxPx: number;
  particleOpacity: number;
  particleBrightness: number;
  particleColorMode: ParticleColorMode;
  particleVelocityStretch: boolean;
  particleStretch: number;
  particleStretchMin: number;
  particleStretchSpeed: number;
  particleSpeedCutoff: number;
  particleSlowCutoff: number;
  particleGlowCore: number;
  particleHotCore: number;
  particleBlendMode: ParticleBlendMode;
  particleExponent: number;
  particleBrightnessBoost: number;
  particleSupportSmoothing: number;
  particleHazeCull: number;
  particleDespeckle: number;
  particleDensityCutoff: number;
  particleDensityRadius: number;
  particleDensityNormalize: number;
  particleDensitySoftness: number;
  particleSupportMask: number;
  particleSupportRadius: number;
  particleSupportNeighbors: number;
  particleSupportFlow: number;
  fastParticleRender: boolean;
  fastNoBloomPost: boolean;
  particleCutoffPrepass: boolean;
  densityLargeHalfRes: boolean;
  densityPassStrength: number;
  densitySmallScale: number;
  densityLargeScale: number;
  densityLargeThreshold: number;
  densityContrastGain: number;
  densityContrastBalance: number;
  densityEmissionPower: number;
  densityOcclusion: number;
  accumulationStrength: number;
  accumulationRadius: number;
  accumulationCurve: number;
  accumulationMemory: number;
  accumulationNoiseReject: number;
  trailOpacity: number;
  fogBrightness: number;
  trailThreshold: number;
  trailColorMode: TrailColorMode;
  fogTint: string;
  particleTint: string;
  renderLayer: "both" | "particles" | "trails" | "density" | "volume-density" | "accumulation" | "debug-voxels";
  palette: "aurora" | "ember" | "spectral";
  filament: number;
  bloomStrength: number;
  bloomThreshold: number;
  bloomRadius: number;
  colorSaturation: number;
  colorContrast: number;
  chromaticAberration: number;
  vignetteStrength: number;
  vignetteSoftness: number;
  streakStrength: number;
  streakLength: number;
  streakVertical: number;
  flareHeight: number;
  flareCutoff: number;
  ribbonFraction: number;
  ribbonWidth: number;
  ribbonTaper: number;
  ribbonLength: number;
  ribbonJoints: number;
  ribbonFadeStart: number;
  ribbonEdgeFade: number;
  cameraYaw: number;
  cameraPitch: number;
  cameraDistance: number;
  cameraPanX: number;
  cameraPanY: number;
  variationMaster: number;
  variationDrift: number;
  variationNoiseMix: number;
  variationFreq: number;
  variationOctaves: number;
  variationGain: number;
  variationLacunarity: number;
  variationSizeAmount: number;
  variationSizeCurve: number;
  variationSizeMin: number;
  variationSizeMax: number;
  variationBrightAmount: number;
  variationBrightCurve: number;
  variationBrightMin: number;
  variationBrightMax: number;
  variationOpacityAmount: number;
  variationOpacityCurve: number;
  variationOpacityMin: number;
  variationOpacityMax: number;
  variationColorAmount: number;
  variationColorCurve: number;
  variationColorMin: number;
  variationColorMax: number;
};

export type ParticleColorMode =
  | "solid"
  | "gradient-inferno"
  | "gradient-magma"
  | "gradient-viridis"
  | "gradient-turbo"
  | "gradient-rainbow"
  | "gradient-spectral"
  | "gradient-plasma"
  | "gradient-cosmic"
  | "gradient-ice"
  | "gradient-ember"
  | "velocity"
  | "velocity-inferno"
  | "velocity-viridis"
  | "velocity-spectral"
  | "velocity-cosmic"
  | "velocity-ice"
  | "audio-magma"
  | "audio-viridis"
  | "audio-turbo"
  | "audio-cosmic"
  | "audio-ice"
  | "audio-ember"
  | "audio-plasma"
  | "cohort"
  | "audio";
